### ISSUE TITLE
[LogicException] Node "parent" does not exist for Node "Twig_Node_Module".

### ISSUE THREAD

**Issue by dawadam** [schmittjoh/twig.js#107]
Since the update of Twig in Version 1.25.0 (2016-09-21), this error occurs at compile time :

```
[Twig_Error_Syntax]                                                          
  An exception has been thrown during the compilation of a template ("Node "p  
  arent" does not exist for Node "Twig_Node_Module".") in "my_view.html.twig".

[LogicException]                                           
  Node "parent" does not exist for Node "Twig_Node_Module".
```

Although "my_view.twig.html" is void of any twig code ...

**Comment by koloszko** [comment]
The problem is in line jms/twig-js/src/TwigJs/Compiler/ModuleCompiler.php:60. Currently it is 
if (null === $node->getNode('parent')) {
and should be from twig 1.25 something like that
if ($node->hasNode('parent') && null === $node->getNode('parent')) {

**Comment by DerManoMann** [comment]
👍

**Comment by ConneXNL** [comment]
Is it just me or does it need a lot more of these hasNode checks? I am getting errors in a lot of compiles.

**Comment by jstuhli** [comment]
PR #109 should fix this, we have it working in production with twig v1.28.2. The changes are simple and should cause no BC breaks.
