### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DerManoMann** [schmittjoh/twig.js#110]
Hi there,

I know some projects do take time to get updated, but is this still being maintained? I am particularly interested in getting https://github.com/schmittjoh/twig.js/pull/109 merged as that stopps us from updating to the latest twig version...

Ta, martin

**Comment by hnrysmth** [comment]
I still keep an eye on PRs and stuff yeah. But I'm lacking the time to do the usual back-and-forth to get things merged sadly. In the case of #109 for example, it seems great, but when I tried running the test suite with Twig 1.25 on that branch it failed, and then I had to run off and do something else and didn't have time to follow up.

**Comment by DerManoMann** [comment]
Fair enough. I've created PR #111 - hopefully that works better. 

Cheers, mano

**Comment by sinasalek** [comment]
I added it to composer for now until the stable version becomes available. tx

**Comment by DerManoMann** [comment]
I guess mi original question is answered :)
