### ISSUE TITLE
Status of the project 

### ISSUE THREAD

**Issue by MI-LA01** [schmittjoh/twig.js#94]
Hello, 

I'm using this project since 2 years, we are migrating some third party libs on our frontend and i've a couple of questions, if you could kindly answer, it would help us in our choices. 
- Is the project is always maintained ? 
- Do you plan to merge pull-request ? 
- I did not seen any push on master since the last year, meaning do you considering this project as deprecated ? 
- If so, do you recommend alternatives ? 

Thanks by advance

**Comment by oleg-andreyev** [comment]
First of all, thanks for great project!
I also curious about this project. :)

**Comment by MI-LA01** [comment]
1 week, no reply

@oleg-andreyev :
i guess we have a first answer...

**Comment by hnrysmth** [comment]
Hey @MI-LA01, sorry for the slow reply :smile:

The project isn't totally unmaintained, it's just reached a really really stable point in its lifecycle. I'm aware of at least one very large-scale production deployment of twig.js where it pretty much always "just works". We don't see a lot of new bug reports, which means there isn't much reason to push new commits.

There _are_ missing features still but the demand to implement them just doesn't seem to exist. A good PR that fixed a bug or added a filter from the list in the README would almost certainly get reviewed and merged. Only thing is it might take a week or two for me or Johannes to notice the PR and start looking at it!

So yeah the project's not dead 😃

**Comment by oleg-andreyev** [comment]
@hnrysmth great news.
If project isn't dead, I'll be glad to prepare some PRs from https://github.com/schmittjoh/twig.js/compare/master...oleg-andreyev:fixing-issues

**Comment by hnrysmth** [comment]
@oleg-andreyev lovely idea, please do!

If any of the stuff in the branch fixes a bug or adds functionality then the ideal thing would be to accompany the PRs with new integrations tests. See https://github.com/schmittjoh/twig.js/tree/master/tests/TwigJs/Tests/Fixture/integration/tests for examples :smile:

**Comment by MI-LA01** [comment]
Sorry guys for my delay and thanks @hnrysmth for your great feedback.
